# Importando arquivos Excel
## Lendo arquivos xlsx

In [5]:
import pandas as pd

tabela_vendas = pd.read_excel('./datasets/vendas.xlsx', sheet_name="Sheet1", index_col=0, decimal=',')
tabela_vendas

,id_venda,filial,vendedor,produto,cliente_nome,cliente_genero,forma_pagamento
data,,,,,,,
2023-01-20 08:00:56.384,0,Canoas,Luis Fernando,Tenis Nike,Sabrina Rieke,feminino,credito
2023-01-20 08:50:58.756,1,Florianópolis,Mario Sérgio,Tenis Adidas,Patsy Lovell,feminino,credito
2023-01-20 11:44:56.777,2,Canoas,Carlos Henrique,Tenis Adidas,John Crandall,masculino,credito
2023-01-20 12:07:58.026,3,Caxias do Sul,Rodrigo Vanzeloti,Tenis Adidas,Mildred Mcleod,feminino,credito
2023-01-20 12:49:56.607,4,São Paulo,Cassia Moraes,Tenis NB,Robert Mccormick,masculino,credito
...,...,...,...,...,...,...,...
2023-09-26 08:39:58.719,1995,Porto Alegre,Luiza Cherobini,Tenis Nike,Glenn Johnson,masculino,credito
2023-09-26 09:45:56.917,1996,Lajeado,Juliano Faccioni,Tenis Adidas,Robert Roop,masculino,boleto
2023-09-26 12:22:56.383,1997,Canoas,Luis Fernando,Tenis Adidas,Mary Berg,feminino,credito
2023-09-26 13:01:57.747,1998,Lajeado,Adriano Soares,Tenis NB,Dianna Alcorn,feminino,credito
2023-09-26 16:32:56.888,1999,São Paulo,Cassia Moraes,Tenis Fila,Isabelle Mercado,feminino,credito

In [9]:

tabela_vendas = pd.read_csv('./datasets/vendas.csv', sep=';', index_col=0, decimal=',')
tabela_vendas

,id_venda,filial,vendedor,produto,cliente_nome,cliente_genero,forma_pagamento
data,,,,,,,
2023-01-20 08:00:56.384224,0,Canoas,Luis Fernando,Tenis Nike,Sabrina Rieke,feminino,credito
2023-01-20 08:50:58.755843,1,Florianópolis,Mario Sérgio,Tenis Adidas,Patsy Lovell,feminino,credito
2023-01-20 11:44:56.776745,2,Canoas,Carlos Henrique,Tenis Adidas,John Crandall,masculino,credito
2023-01-20 12:07:58.025749,3,Caxias do Sul,Rodrigo Vanzeloti,Tenis Adidas,Mildred Mcleod,feminino,credito
2023-01-20 12:49:56.606703,4,São Paulo,Cassia Moraes,Tenis NB,Robert Mccormick,masculino,credito
...,...,...,...,...,...,...,...
2023-09-26 08:39:58.718787,1995,Porto Alegre,Luiza Cherobini,Tenis Nike,Glenn Johnson,masculino,credito
2023-09-26 09:45:56.916568,1996,Lajeado,Juliano Faccioni,Tenis Adidas,Robert Roop,masculino,boleto
2023-09-26 12:22:56.382995,1997,Canoas,Luis Fernando,Tenis Adidas,Mary Berg,feminino,credito
2023-09-26 13:01:57.747415,1998,Lajeado,Adriano Soares,Tenis NB,Dianna Alcorn,feminino,credito
2023-09-26 16:32:56.888289,1999,São Paulo,Cassia Moraes,Tenis Fila,Isabelle Mercado,feminino,credito